### ISSUE TITLE
Moleculesの作成

### ISSUE THREAD

**Issue by Najah7** [Najah7/peta-peta#12]
# TODO

- [x] 名前付きAvatorItem（アバター+名前）
- [x] テキスト付きアイコンボタン（アイコン＋テキスト+ボタン）
- [ ] フォロワー用のモーダル👈[MUIのモーダル](https://mui.com/material-ui/react-modal/#basic-modal)
- [x] コメント用のインプット
